### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by alexdrag** [jelovac/bitly4laravel#15]
I tried to integrate into my Laravel 4 project your package (master version). But I saw an error
![screenshot 2015-03-05 10 16 15](https://cloud.githubusercontent.com/assets/2320238/6502430/9d72661c-c323-11e4-8850-d9aa75e0d4bc.png)

I tried version 2.* and it worked. I checked this file vendor/jelovac/bitly4laravel/src/Jelovac/Bitly4laravel/ServiceProviders/Laravel4ServiceProvider.php and in version two you have one line that is missing in version 3:

use Jelovac\Bitly4laravel\Bitly4laravel;

Maybe I missed something in configuration, or maybe this is an issue.

Thanks,
Aleksandar

**Comment by jelovac** [comment]
Yes indeed that's an issue thank you for reporting it.
