### ISSUE TITLE
INVALID_ARG_ACCESS_TOKEN

### ISSUE THREAD

**Issue by purplegriffon** [jelovac/bitly4laravel#16]
Getting an INVALID_ARG_ACCESS_TOKEN in the response for 'status_txt' when the access_token is correct in the package config.

**Comment by jelovac** [comment]
Tnx for reporting, which version of the package are you using?

----- Reply message -----

**Comment by purplegriffon** [comment]
No problem. It’s the latest stable release 3.0.2. Cheers!

From: Vladimir Jelovac
Reply-To: jelovac/bitly4laravel
Date: Friday, 20 March 2015 06:21
To: jelovac/bitly4laravel
Cc: Gareth Daine
Subject: Re: [bitly4laravel] INVALID_ARG_ACCESS_TOKEN (#16)

Tnx for reporting, which version of the package are you using?

----- Reply message -----

**Comment by jelovac** [comment]
Greetings Gareth,

I just tested this on my local dev machine and everything seems fine. Are you sure that the access token you are entering is correct? 

I have tested package shorten and expand methods and they return the correct response.

Tested on Laravel Homestead build with Laravel 5 basic install.

**Comment by purplegriffon** [comment]
Yes, definitely using the correct access token, plus I'm using Laravel 4.

**Comment by jelovac** [comment]
Ok, will test it today on Laravel 4.

----- Reply message -----

**Comment by jelovac** [comment]
Confirmed, this affects both V3 and V2.

**Comment by jelovac** [comment]
Hi, the issue should be fixed now, tested on both Laravel 4 and Laravel 5.
