### ISSUE TITLE
Guzzle upgrade to v6

### ISSUE THREAD

**Issue by jelovac** [jelovac/bitly4laravel#23]
Greetings,

This issue concerns the upgrade of Guzzle library to v6 used by this package.

The upgrade plan is the following:
- change the composer file to require v6
- migrate guzzle v5 logic to v6

rgds,
Vladimir

**Comment by trevorgehman** [comment]
Any update on this?

**Comment by mbarwick83** [comment]
+1 for an update on this

**Comment by jelovac** [comment]
Sorry guys for the late update, I currently don't have spare time to develop this myself so if you create a good pull request I would gladly approve it.

Kind regards,
Vladimir

**Comment by mbarwick83** [comment]
@MyoStudio has a `fixGuzzleVersionTo6.0` branch that I'm using. Works like a charm. Need to `json_decode()` response though - as Guzzle 6 doesn't have the `->toJson()` or whatever it was < 6. https://github.com/MyoStudio/bitly4laravel
