### ISSUE TITLE
Basic configuration

### ISSUE THREAD

**Issue by jesusvazquez** [jelovac/bitly4laravel#24]
Hi,

I'm trying to use your package but I'm stuck with the config file. Don't know where should I place the bitly api key or the public client id.

Can you share a basic example? Not just the template that comes with the package.

Thanks!

**Comment by jelovac** [comment]
Greetings,

When you install the package you need to publish the config using the following command:

For **Laravel 5** use: **php artisan vendor:publish**

For **Laravel 4** use: **php artisan config:publish jelovac/bitly4laravel**

 A copy of the [config.php](https://github.com/jelovac/bitly4laravel/blob/master/src/config/config.php) will be placed into your project config directory.

Then you should generate Bit.ly access token by visiting their website: https://bitly.com/a/oauth_apps

Place the access token in the generated config and the will be it.

regards,
Vladimir

PS: This package doesn't support out of the box the old auth methods via api key so you need to generate the OAuth token at their website.

**Comment by jesusvazquez** [comment]
Hey jelovac,

I've being trying what you said. Once I create an application in the bitly page, they provide me with two keys, the Client ID and the Client Secret. I tried with both but I'm getting the error all the time

```
array:3 [▼
  "data" => []
  "status_code" => 500
  "status_txt" => "INVALID_ARG_ACCESS_TOKEN"
]
```
My steps are:
1) php artisan vendor:publish
2) create the applicaton in bitly
3) edit file config/bitly4laravel.php and modify the first attribute "acces_token" to place the key (probably the client secret) that bitly provides.

Am I missning something? 

Thanks!

**Comment by jelovac** [comment]
You are confusing access token with  client secret and client id. They are not the same. Have a look at this youtube video how to get access token: http://bit.ly/1LBsJ7i

----- Reply message -----

**Comment by jesusvazquez** [comment]
It does work. Thanks :)
