### ISSUE TITLE
Laravel 5 error

### ISSUE THREAD

**Issue by peterlevin** [jelovac/bitly4laravel#25]
Invalid variable type detected! The variable must be type "String", "NULL" type passed.

Followed instructions. 

Added use Bitly; to my controller and getting above error with:

$test = Bitly::shorten('http://google.com/');
        
return $test;

**Comment by peterlevin** [comment]
hold up! Think i figured it out...stand by!

**Comment by peterlevin** [comment]
Nope, can't figure it out. Added acccess token to config and can't get it to work.

**Comment by briff** [comment]
Works for me out of the box on laravel 5.2

**Comment by jelovac** [comment]
Couldn't reproduce this issue. Closing for now.

**Comment by freel132** [comment]
have same issue
