### ISSUE TITLE
Invalid variable type detected! The variable must be type "String", "NULL" type passed.

### ISSUE THREAD

**Issue by freel132** [jelovac/bitly4laravel#26]
Invalid variable type detected! The variable must be type "String", "NULL" type passed.

any ideas what's the problem?

**Comment by jelovac** [comment]
Greetings freel132,

Can you provide me with more info so I can identify what the problem is? For example PHP version, Laravel version and the method you used when the error occurred?

rgds,
Vladimir

**Comment by freel132** [comment]
Hello, 
Laravel Framework version 5.2.29
PHP Version 5.6.10

I already solving my problem different way. but as I remember I were trying to use this in my view and in controller. 

in view:
{{\Bitly::shorten('http://google.com/')}}

in controller:
$link = Bitly::shorten('http://google.com/');

I hope I remmeber correcly ;)
I need this solution when I am sharing my post on fb. As you probably know FB cache all information so all the time I want to provide other url.
thx
