### ISSUE TITLE
Composer require issue

### ISSUE THREAD

**Issue by rohitkhatri** [jelovac/bitly4laravel#27]
On trying this command in terminal `composer require "jelovac/bitly4laravel": "3.*"` I got the following error:

Could not find package 3.\* at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Can anybody tell me what I'm doing wrong?

**Comment by jelovac** [comment]
Hi @rohitkhatri ,

Thank you for reporting this issue. When I developed this package I used composer's "minimum-stability": "dev" which is still present and therefore the reason why you are receiving this error.

As a workaround until I fix this you can do the following:

Set in composer.json:

> "minimum-stability": "dev",
"prefer-stable" : true

or:

> "require": {
        "jelovac/bitly4laravel": "3.*@dev"
    },

Kind regards,
Vladimir

**Comment by rohitkhatri** [comment]
Thanks
