### ISSUE TITLE
SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by bulletinmybeard** [jelovac/bitly4laravel#3]
I got this error message while shorten a url. After extending the curl request, all works fine! Please add _CURLOPT_SSL_VERIFYHOST_ and _CURLOPT_SSL_VERIFYPEER_ to the _curl_setopt_array()_ in _Connection.php_ as an hotfix.

``` php...
$options[CURLOPT_SSL_VERIFYHOST] = 0;
$options[CURLOPT_SSL_VERIFYPEER] = 0;

curl_setopt_array($curl, $options);
```

cheers

**Comment by rcrisp** [comment]
+1 - I am getting SSL Errors.  Can you please let me know how I can disable the SSL checks, and preferably add it to the documentation?
