### ISSUE TITLE
"Expand" and "Info" functions don't filter URL

### ISSUE THREAD

**Issue by FranLara** [jelovac/bitly4laravel#32]
The function "Expand" as well as "Info" don't recognise the Bit.ly URL's as URL's.

In the condition:
`if (filter_var($shortURLOrHash, FILTER_VALIDATE_URL) === true) {` (lines 371 and 407)

The `===` gives always `false` and takes the url like a hash. 

If change them to `==` works properly.  

Other solution is switching the condition:
`if (filter_var($shortURLOrHash, FILTER_VALIDATE_URL) === false) {
            $params['hash'] = $shortURLOrHash;
        } else {
            $params['shortUrl'] = $shortURLOrHash;
        }`
That works properly too.

**Comment by FranLara** [comment]
@jelovac I'm trying to do a "Pull Request" but I'm not allowed. I paste the code below (was tested and works properly):

```
public function expand($shortURLOrHash)
    {
        $params = array();
        if (filter_var($shortURLOrHash, FILTER_VALIDATE_URL) === false) {
            $params['hash'] = $shortURLOrHash;
        } else {
            $params['shortUrl'] = $shortURLOrHash;
        }
        return $this->make('expand', $params);
    }

public function info($shortURLOrHash, $expandUser = null)
    {
        $params = array();

        if (filter_var($shortURLOrHash, FILTER_VALIDATE_URL) === false) {
            $params['hash'] = $shortURLOrHash;
        } else {
            $params['shortUrl'] = $shortURLOrHash;
        }

        if ($expandUser !== null) {
            $params['expand_user'] = $expandUser;
        }

        return $this->make('info', $params);
    }

**Comment by jelovac** [comment]
@FranLara thanks for reporting.

**Comment by FranLara** [comment]
Hi @jelovac Is there any expected day to fix and deploy this bug? Thanks in advance.

**Comment by jelovac** [comment]
Hi @FranLara, sorry for the late response. Currently I do not have spare time to work on this project, I'll try to push your solution as soon as I find some.
